language_models : ["esm2", "protT5", "proteinBERT"]
dimensions : [16, 32, 64, 128]
activation : ["sigmoid"] 
num_components : [0,1,10,100]
frozen_insertions : [False]
use_l2 : [True]
L2_match : [0.]
L2_insert : [1000.]
temperature_mode : ["trainable"]